START TRANSACTION
;
update ignore enrollment_level
set description = "Senior"
where description = "Tenured"
;
insert ignore enrollment_level
set description = "Tenured ALS"
, num_shifts = 2
, pecking_order = 4
, elaboration = "as defined in EMS Duty Policy"
, core_ops_commitment_level_code = (select code from core_ops_commitment_level where name = "Standard")
;
insert ignore enrollment_level
set description = "Tenured BLS"
, num_shifts = 1
, pecking_order = 7
, elaboration = "as defined in EMS Duty Policy"
, core_ops_commitment_level_code = (select code from core_ops_commitment_level where name = "Standard")
;
update enrollment_transition
set disallowed_historical_level_code = (select code from enrollment_level where description = "Tenured BLS")
where required_historical_level_code = (select code from enrollment_level where description = "Senior")
  and valid_next_level_code = (select code from enrollment_level where description = "Senior")
;
insert ignore enrollment_transition (current_level_code,required_historical_level_code,disallowed_historical_level_code,valid_next_level_code,authorized_tier_id) values
((select code from enrollment_level where description = "Admin"),(select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Tenured BLS"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Admin"),(select code from enrollment_level where description = "Regular"),(select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = "Reduced (1)"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Senior"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Tenured BLS"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Admin"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Atypical"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Resigned"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Retired"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Deceased"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Dismissed"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Disabled"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Unknown"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Atypical"),(select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Tenured BLS"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Atypical"),(select code from enrollment_level where description = "Regular"),(select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = "Reduced (1)"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Reduced (1)"),(select code from enrollment_level where description = "Tenured BLS"),NULL,(select code from enrollment_level where description = "Tenured BLS"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Suspended"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Suspended"),(select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Tenured BLS"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Suspended"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = "Reduced (1)"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Transferring"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Transferring"),(select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Tenured BLS"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Transferring"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = "Reduced (1)"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Unknown"),(select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Tenured BLS"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Unknown"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = "Reduced (1)"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Recruit"),(select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Tenured BLS"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Staff"),(select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Tenured BLS"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Staff"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = "Reduced (1)"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "ALS Intern"),(select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Tenured BLS"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "ALS Intern"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = "Reduced (1)"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "College"),(select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Tenured BLS"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "College"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = "Reduced (1)"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "Staff"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "ALS Intern"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = "Tenured BLS"),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = ""),(select code from enrollment_level where description = "College"),(select id from tier where name = "Squad")),
((select code from enrollment_level where description = 'Admin'),(select code from enrollment_level where description = 'Senior'),(select code from enrollment_level where description = 'Tenured ALS'),(select code from enrollment_level where description = 'Senior'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Atypical'),(select code from enrollment_level where description = 'Senior'),(select code from enrollment_level where description = 'Tenured ALS'),(select code from enrollment_level where description = 'Senior'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Reduced (1)'),(select code from enrollment_level where description = 'Senior'),(select code from enrollment_level where description = 'Tenured ALS'),(select code from enrollment_level where description = 'Senior'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Reduced (2)'),(select code from enrollment_level where description = 'Senior'),(select code from enrollment_level where description = 'Tenured ALS'),(select code from enrollment_level where description = 'Senior'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Reduced (3)'),(select code from enrollment_level where description = 'Senior'),(select code from enrollment_level where description = 'Tenured ALS'),(select code from enrollment_level where description = 'Senior'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Suspended'),(select code from enrollment_level where description = 'Senior'),(select code from enrollment_level where description = 'Tenured ALS'),(select code from enrollment_level where description = 'Senior'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Transferring'),(select code from enrollment_level where description = 'Senior'),(select code from enrollment_level where description = 'Tenured ALS'),(select code from enrollment_level where description = 'Senior'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Unknown'),(select code from enrollment_level where description = 'Senior'),(select code from enrollment_level where description = 'Tenured ALS'),(select code from enrollment_level where description = 'Senior'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Recruit'),(select code from enrollment_level where description = 'Senior'),(select code from enrollment_level where description = 'Tenured ALS'),(select code from enrollment_level where description = 'Senior'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Staff'),(select code from enrollment_level where description = 'Senior'),(select code from enrollment_level where description = 'Tenured ALS'),(select code from enrollment_level where description = 'Senior'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'ALS Intern'),(select code from enrollment_level where description = 'Senior'),(select code from enrollment_level where description = 'Tenured ALS'),(select code from enrollment_level where description = 'Senior'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'College'),(select code from enrollment_level where description = 'Senior'),(select code from enrollment_level where description = 'Tenured ALS'),(select code from enrollment_level where description = 'Senior'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Admin'),(select code from enrollment_level where description = 'Tenured ALS'),NULL,(select code from enrollment_level where description = 'Tenured ALS'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Admin'),(select code from enrollment_level where description = 'Regular'),(select code from enrollment_level where description = 'Tenured ALS'),(select code from enrollment_level where description = 'Reduced (1)'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Senior'),NULL,NULL,(select code from enrollment_level where description = 'Tenured ALS'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Tenured ALS'),NULL,NULL,(select code from enrollment_level where description = 'Admin'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Tenured ALS'),NULL,NULL,(select code from enrollment_level where description = 'Atypical'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Tenured ALS'),NULL,NULL,(select code from enrollment_level where description = 'Resigned'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Tenured ALS'),NULL,NULL,(select code from enrollment_level where description = 'Retired'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Tenured ALS'),NULL,NULL,(select code from enrollment_level where description = 'Deceased'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Tenured ALS'),NULL,NULL,(select code from enrollment_level where description = 'Dismissed'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Tenured ALS'),NULL,NULL,(select code from enrollment_level where description = 'Disabled'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Tenured ALS'),NULL,NULL,(select code from enrollment_level where description = 'Unknown'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Atypical'),(select code from enrollment_level where description = 'Tenured ALS'),NULL,(select code from enrollment_level where description = 'Tenured ALS'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Atypical'),(select code from enrollment_level where description = 'Regular'),(select code from enrollment_level where description = 'Tenured ALS'),(select code from enrollment_level where description = 'Reduced (1)'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Reduced (1)'),(select code from enrollment_level where description = 'Tenured ALS'),NULL,(select code from enrollment_level where description = 'Tenured ALS'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Tenured ALS'),NULL,NULL,(select code from enrollment_level where description = 'Suspended'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Suspended'),(select code from enrollment_level where description = 'Tenured ALS'),NULL,(select code from enrollment_level where description = 'Tenured ALS'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Suspended'),NULL,(select code from enrollment_level where description = 'Tenured ALS'),(select code from enrollment_level where description = 'Reduced (1)'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Tenured ALS'),NULL,NULL,(select code from enrollment_level where description = 'Transferring'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Transferring'),(select code from enrollment_level where description = 'Tenured ALS'),NULL,(select code from enrollment_level where description = 'Tenured ALS'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Transferring'),NULL,(select code from enrollment_level where description = 'Tenured ALS'),(select code from enrollment_level where description = 'Reduced (1)'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Unknown'),(select code from enrollment_level where description = 'Tenured ALS'),NULL,(select code from enrollment_level where description = 'Tenured ALS'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Unknown'),NULL,(select code from enrollment_level where description = 'Tenured ALS'),(select code from enrollment_level where description = 'Reduced (1)'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Recruit'),(select code from enrollment_level where description = 'Tenured ALS'),NULL,(select code from enrollment_level where description = 'Tenured ALS'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Staff'),(select code from enrollment_level where description = 'Tenured ALS'),NULL,(select code from enrollment_level where description = 'Tenured ALS'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Staff'),NULL,(select code from enrollment_level where description = 'Tenured ALS'),(select code from enrollment_level where description = 'Reduced (1)'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'ALS Intern'),(select code from enrollment_level where description = 'Tenured ALS'),NULL,(select code from enrollment_level where description = 'Tenured ALS'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'ALS Intern'),NULL,(select code from enrollment_level where description = 'Tenured ALS'),(select code from enrollment_level where description = 'Reduced (1)'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'College'),(select code from enrollment_level where description = 'Tenured ALS'),NULL,(select code from enrollment_level where description = 'Tenured ALS'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'College'),NULL,(select code from enrollment_level where description = 'Tenured ALS'),(select code from enrollment_level where description = 'Reduced (1)'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Tenured ALS'),NULL,NULL,(select code from enrollment_level where description = 'Staff'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Tenured ALS'),NULL,NULL,(select code from enrollment_level where description = 'ALS Intern'),(select id from tier where name = 'Squad')),
((select code from enrollment_level where description = 'Tenured ALS'),NULL,NULL,(select code from enrollment_level where description = 'College'),(select id from tier where name = 'Squad'))
;
COMMIT