START TRANSACTION
;
ALTER TABLE `analysis`
  CHANGE COLUMN `agency` `agency` ENUM('KVRS','PVRS','DCVRS','PACHVRS','CBVRS','VBVRS','OPVRS','CVRS','BVRS','SVRS') NOT NULL DEFAULT 'KVRS'
;
ALTER TABLE `manifest`
  CHANGE COLUMN `agency` `agency` ENUM('KVRS','PVRS','DCVRS','PACHVRS','CBVRS','VBVRS','OPVRS','CVRS','BVRS','SVRS') NOT NULL DEFAULT 'KVRS'
;
ALTER TABLE `resident_base`
  CHANGE COLUMN `agency` `agency` ENUM('KVRS','PVRS','DCVRS','PACHVRS','CBVRS','VBVRS','OPVRS','CVRS','BVRS','SVRS') CHARACTER SET 'latin1' NOT NULL DEFAULT 'KVRS'
;
COMMIT