DROP TABLE IF EXISTS rank;
CREATE TABLE IF NOT EXISTS rank (
  id SERIAL,
  agency_id INTEGER UNSIGNED DEFAULT 0 NOT NULL,
  name VARCHAR(31) NOT NULL,
  pecking_order SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY(id),
  UNIQUE (id)
)
ENGINE = InnoDB;
