select cad_num
, last_name
, first_name
, FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020),1) as 2020_duty_hours
, FORMAT((IFNULL((select num_shifts from enrollment_level where code = jan_code),0) + IFNULL((select num_shifts from enrollment_level where code = feb_code),0) + IFNULL((select num_shifts from enrollment_level where code = mar_code),0) + IFNULL((select num_shifts from enrollment_level where code = apr_code),0) + IFNULL((select num_shifts from enrollment_level where code = may_code),0) + IFNULL((select num_shifts from enrollment_level where code = jun_code),0) + IFNULL((select num_shifts from enrollment_level where code = jul_code),0) + IFNULL((select num_shifts from enrollment_level where code = aug_code),0) + IFNULL((select num_shifts from enrollment_level where code = sep_code),0) + IFNULL((select num_shifts from enrollment_level where code = oct_code),0) + IFNULL((select num_shifts from enrollment_level where code = nov_code),0) + IFNULL((select num_shifts from enrollment_level where code = dec_code),0))*12,1) as 2020_base_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020),1)/FORMAT((IFNULL((select num_shifts from enrollment_level where code = jan_code),0) + IFNULL((select num_shifts from enrollment_level where code = feb_code),0) + IFNULL((select num_shifts from enrollment_level where code = mar_code),0) + IFNULL((select num_shifts from enrollment_level where code = apr_code),0) + IFNULL((select num_shifts from enrollment_level where code = may_code),0) + IFNULL((select num_shifts from enrollment_level where code = jun_code),0) + IFNULL((select num_shifts from enrollment_level where code = jul_code),0) + IFNULL((select num_shifts from enrollment_level where code = aug_code),0) + IFNULL((select num_shifts from enrollment_level where code = sep_code),0) + IFNULL((select num_shifts from enrollment_level where code = oct_code),0) + IFNULL((select num_shifts from enrollment_level where code = nov_code),0) + IFNULL((select num_shifts from enrollment_level where code = dec_code),0))*12,1)),0),'%') as 2020_pct_of_base
, FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-01-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = jan_code),0))*12 + IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-02-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = feb_code),0))*12 + IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-03-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = mar_code),0))*12 + IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-04-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = apr_code),0))*12 + IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-05-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = may_code),0))*12 + IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-06-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = jun_code),0))*12 + IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-07-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = jul_code),0))*12 + IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-08-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = aug_code),0))*12 + IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-09-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = sep_code),0))*12 + IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-10-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = oct_code),0))*12 + IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-11-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = nov_code),0))*12 + IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-12-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = dec_code),0))*12,1) as 2020_effective_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020),1)/FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-01-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = jan_code),0))*12 + IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-02-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = feb_code),0))*12 + IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-03-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = mar_code),0))*12 + IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-04-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = apr_code),0))*12 + IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-05-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = may_code),0))*12 + IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-06-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = jun_code),0))*12 + IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-07-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = jul_code),0))*12 + IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-08-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = aug_code),0))*12 + IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-09-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = sep_code),0))*12 + IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-10-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = oct_code),0))*12 + IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-11-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = nov_code),0))*12 + IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-12-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = dec_code),0))*12,1)),0),'%') as 2020_pct_of_effective

, FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 1),1) as jan_duty_hours
, IFNULL((select description from enrollment_level where code = jan_code),'(na)') as jan_enrollment
, IFNULL(FORMAT((select num_shifts from enrollment_level where code = jan_code)*12,1),0) as jan_base_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 1),1)/FORMAT((select num_shifts from enrollment_level where code = jan_code)*12,1)),0),'%') as jan_pct_of_base
, IFNULL((select description from leave_of_absence l join kind_of_leave_code_description_map k on (k.code=l.kind_of_leave_code) where l.member_id = subquery.member_id and '2020-01-15' between l.start_date and l.end_date),'(none)') as jan_leave
, FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-01-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = jan_code),0))*12,1) as jan_effective_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 1),1)/FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-01-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = jan_code),0))*12,1)),0),'%') as jan_pct_of_effective

, FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 2),1) as feb_duty_hours
, IFNULL((select description from enrollment_level where code = feb_code),'(na)') as feb_enrollment
, IFNULL(FORMAT((select num_shifts from enrollment_level where code = feb_code)*12,1),0) as feb_base_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 2),1)/FORMAT((select num_shifts from enrollment_level where code = feb_code)*12,1)),0),'%') as feb_pct_of_base
, IFNULL((select description from leave_of_absence l join kind_of_leave_code_description_map k on (k.code=l.kind_of_leave_code) where l.member_id = subquery.member_id and '2020-02-15' between l.start_date and l.end_date),'(none)') as feb_leave
, FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-02-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = feb_code),0))*12,1) as feb_effective_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 2),1)/FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-02-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = feb_code),0))*12,1)),0),'%') as feb_pct_of_effective

, FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 3),1) as mar_duty_hours
, IFNULL((select description from enrollment_level where code = mar_code),'(na)') as mar_enrollment
, IFNULL(FORMAT((select num_shifts from enrollment_level where code = mar_code)*12,1),0) as mar_base_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 3),1)/FORMAT((select num_shifts from enrollment_level where code = mar_code)*12,1)),0),'%') as mar_pct_of_base
, IFNULL((select description from leave_of_absence l join kind_of_leave_code_description_map k on (k.code=l.kind_of_leave_code) where l.member_id = subquery.member_id and '2020-03-15' between l.start_date and l.end_date),'(none)') as mar_leave
, FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-03-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = mar_code),0))*12,1) as mar_effective_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 3),1)/FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-03-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = mar_code),0))*12,1)),0),'%') as mar_pct_of_effective

, FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 4),1) as apr_duty_hours
, IFNULL((select description from enrollment_level where code = apr_code),'(na)') as apr_enrollment
, IFNULL(FORMAT((select num_shifts from enrollment_level where code = apr_code)*12,1),0) as apr_base_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 4),1)/FORMAT((select num_shifts from enrollment_level where code = apr_code)*12,1)),0),'%') as apr_pct_of_base
, IFNULL((select description from leave_of_absence l join kind_of_leave_code_description_map k on (k.code=l.kind_of_leave_code) where l.member_id = subquery.member_id and '2020-04-15' between l.start_date and l.end_date),'(none)') as apr_leave
, FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-04-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = apr_code),0))*12,1) as apr_effective_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 4),1)/FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-04-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = apr_code),0))*12,1)),0),'%') as apr_pct_of_effective

, FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 5),1) as may_duty_hours
, IFNULL((select description from enrollment_level where code = may_code),'(na)') as may_enrollment
, IFNULL(FORMAT((select num_shifts from enrollment_level where code = may_code)*12,1),0) as may_base_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 5),1)/FORMAT((select num_shifts from enrollment_level where code = may_code)*12,1)),0),'%') as may_pct_of_base
, IFNULL((select description from leave_of_absence l join kind_of_leave_code_description_map k on (k.code=l.kind_of_leave_code) where l.member_id = subquery.member_id and '2020-05-15' between l.start_date and l.end_date),'(none)') as may_leave
, FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-05-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = may_code),0))*12,1) as may_effective_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 5),1)/FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-05-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = may_code),0))*12,1)),0),'%') as may_pct_of_effective

, FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 6),1) as jun_duty_hours
, IFNULL((select description from enrollment_level where code = jun_code),'(na)') as jun_enrollment
, IFNULL(FORMAT((select num_shifts from enrollment_level where code = jun_code)*12,1),0) as jun_base_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 6),1)/FORMAT((select num_shifts from enrollment_level where code = jun_code)*12,1)),0),'%') as jun_pct_of_base
, IFNULL((select description from leave_of_absence l join kind_of_leave_code_description_map k on (k.code=l.kind_of_leave_code) where l.member_id = subquery.member_id and '2020-06-15' between l.start_date and l.end_date),'(none)') as jun_leave
, FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-06-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = jun_code),0))*12,1) as jun_effective_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 6),1)/FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-06-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = jun_code),0))*12,1)),0),'%') as jun_pct_of_effective

, FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 7),1) as jul_duty_hours
, IFNULL((select description from enrollment_level where code = jul_code),'(na)') as jul_enrollment
, IFNULL(FORMAT((select num_shifts from enrollment_level where code = jul_code)*12,1),0) as jul_base_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 7),1)/FORMAT((select num_shifts from enrollment_level where code = jul_code)*12,1)),0),'%') as jul_pct_of_base
, IFNULL((select description from leave_of_absence l join kind_of_leave_code_description_map k on (k.code=l.kind_of_leave_code) where l.member_id = subquery.member_id and '2020-07-15' between l.start_date and l.end_date),'(none)') as jul_leave
, FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-07-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = jul_code),0))*12,1) as jul_effective_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 7),1)/FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-07-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = jul_code),0))*12,1)),0),'%') as jul_pct_of_effective

, FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 8),1) as aug_duty_hours
, IFNULL((select description from enrollment_level where code = aug_code),'(na)') as aug_enrollment
, IFNULL(FORMAT((select num_shifts from enrollment_level where code = aug_code)*12,1),0) as aug_base_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 8),1)/FORMAT((select num_shifts from enrollment_level where code = aug_code)*12,1)),0),'%') as aug_pct_of_base
, IFNULL((select description from leave_of_absence l join kind_of_leave_code_description_map k on (k.code=l.kind_of_leave_code) where l.member_id = subquery.member_id and '2020-08-15' between l.start_date and l.end_date),'(none)') as aug_leave
, FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-08-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = aug_code),0))*12,1) as aug_effective_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 8),1)/FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-08-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = aug_code),0))*12,1)),0),'%') as aug_pct_of_effective

, FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 9),1) as sep_duty_hours
, IFNULL((select description from enrollment_level where code = sep_code),'(na)') as sep_enrollment
, IFNULL(FORMAT((select num_shifts from enrollment_level where code = sep_code)*12,1),0) as sep_base_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 9),1)/FORMAT((select num_shifts from enrollment_level where code = sep_code)*12,1)),0),'%') as sep_pct_of_base
, IFNULL((select description from leave_of_absence l join kind_of_leave_code_description_map k on (k.code=l.kind_of_leave_code) where l.member_id = subquery.member_id and '2020-09-15' between l.start_date and l.end_date),'(none)') as sep_leave
, FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020--0915' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = sep_code),0))*12,1) as sep_effective_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 9),1)/FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-09-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = sep_code),0))*12,1)),0),'%') as sep_pct_of_effective

, FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 10),1) as oct_duty_hours
, IFNULL((select description from enrollment_level where code = oct_code),'(na)') as oct_enrollment
, IFNULL(FORMAT((select num_shifts from enrollment_level where code = oct_code)*12,1),0) as oct_base_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 10),1)/FORMAT((select num_shifts from enrollment_level where code = oct_code)*12,1)),0),'%') as oct_pct_of_base
, IFNULL((select description from leave_of_absence l join kind_of_leave_code_description_map k on (k.code=l.kind_of_leave_code) where l.member_id = subquery.member_id and '2020-10-15' between l.start_date and l.end_date),'(none)') as oct_leave
, FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-10-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = oct_code),0))*12,1) as oct_effective_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 10),1)/FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-10-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = oct_code),0))*12,1)),0),'%') as oct_pct_of_effective

, FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 11),1) as nov_duty_hours
, IFNULL((select description from enrollment_level where code = nov_code),'(na)') as nov_enrollment
, IFNULL(FORMAT((select num_shifts from enrollment_level where code = nov_code)*12,1),0) as nov_base_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 11),1)/FORMAT((select num_shifts from enrollment_level where code = nov_code)*12,1)),0),'%') as nov_pct_of_base
, IFNULL((select description from leave_of_absence l join kind_of_leave_code_description_map k on (k.code=l.kind_of_leave_code) where l.member_id = subquery.member_id and '2020-11-15' between l.start_date and l.end_date),'(none)') as nov_leave
, FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-11-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = nov_code),0))*12,1) as nov_effective_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 11),1)/FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-11-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = nov_code),0))*12,1)),0),'%') as nov_pct_of_effective

, FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 12),1) as dec_duty_hours
, IFNULL((select description from enrollment_level where code = dec_code),'(na)') as dec_enrollment
, IFNULL(FORMAT((select num_shifts from enrollment_level where code = dec_code)*12,1),0) as dec_base_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 12),1)/FORMAT((select num_shifts from enrollment_level where code = dec_code)*12,1)),0),'%') as dec_pct_of_base
, IFNULL((select description from leave_of_absence l join kind_of_leave_code_description_map k on (k.code=l.kind_of_leave_code) where l.member_id = subquery.member_id and '2020-12-15' between l.start_date and l.end_date),'(none)') as dec_leave
, FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-12-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = dec_code),0))*12,1) as dec_effective_obligation
, CONCAT(IFNULL(ROUND(100*FORMAT((select IFNULL(sum(TIME_TO_SEC(TIMEDIFF(muster_to_logoff_timespan,muster_to_logon_timespan))/3600*be_selected),0) from schedule_assignment where member_id = subquery.member_id and YEAR(nominal_day) = 2020 and MONTH(nominal_day) = 12),1)/FORMAT(IFNULL((select num_obliged_shifts from leave_of_absence where member_id = subquery.member_id and '2020-12-15' between start_date and end_date),IFNULL((select num_shifts from enrollment_level where code = dec_code),0))*12,1)),0),'%') as dec_pct_of_effective
from
  (
  select member.id as member_id
  , cad_num
  , last_name
  , first_name
  , (select level_code from enrollment_history h join enrollment_level l on (l.code=h.level_code and l.pecking_order < 84) where member_id = member.id and '2020-01-15' between h.start_date and IFNULL(h.end_date,'9999-12-31') limit 1) as jan_code
  , (select level_code from enrollment_history h join enrollment_level l on (l.code=h.level_code and l.pecking_order < 84) where member_id = member.id and '2020-02-15' between h.start_date and IFNULL(h.end_date,'9999-12-31') limit 1) as feb_code
  , (select level_code from enrollment_history h join enrollment_level l on (l.code=h.level_code and l.pecking_order < 84) where member_id = member.id and '2020-03-15' between h.start_date and IFNULL(h.end_date,'9999-12-31') limit 1) as mar_code
  , (select level_code from enrollment_history h join enrollment_level l on (l.code=h.level_code and l.pecking_order < 84) where member_id = member.id and '2020-04-15' between h.start_date and IFNULL(h.end_date,'9999-12-31') limit 1) as apr_code
  , (select level_code from enrollment_history h join enrollment_level l on (l.code=h.level_code and l.pecking_order < 84) where member_id = member.id and '2020-05-15' between h.start_date and IFNULL(h.end_date,'9999-12-31') limit 1) as may_code
  , (select level_code from enrollment_history h join enrollment_level l on (l.code=h.level_code and l.pecking_order < 84) where member_id = member.id and '2020-06-15' between h.start_date and IFNULL(h.end_date,'9999-12-31') limit 1) as jun_code
  , (select level_code from enrollment_history h join enrollment_level l on (l.code=h.level_code and l.pecking_order < 84) where member_id = member.id and '2020-07-15' between h.start_date and IFNULL(h.end_date,'9999-12-31') limit 1) as jul_code
  , (select level_code from enrollment_history h join enrollment_level l on (l.code=h.level_code and l.pecking_order < 84) where member_id = member.id and '2020-08-15' between h.start_date and IFNULL(h.end_date,'9999-12-31') limit 1) as aug_code
  , (select level_code from enrollment_history h join enrollment_level l on (l.code=h.level_code and l.pecking_order < 84) where member_id = member.id and '2020-09-15' between h.start_date and IFNULL(h.end_date,'9999-12-31') limit 1) as sep_code
  , (select level_code from enrollment_history h join enrollment_level l on (l.code=h.level_code and l.pecking_order < 84) where member_id = member.id and '2020-10-15' between h.start_date and IFNULL(h.end_date,'9999-12-31') limit 1) as oct_code
  , (select level_code from enrollment_history h join enrollment_level l on (l.code=h.level_code and l.pecking_order < 84) where member_id = member.id and '2020-11-15' between h.start_date and IFNULL(h.end_date,'9999-12-31') limit 1) as nov_code
  , (select level_code from enrollment_history h join enrollment_level l on (l.code=h.level_code and l.pecking_order < 84) where member_id = member.id and '2020-12-15' between h.start_date and IFNULL(h.end_date,'9999-12-31') limit 1) as dec_code
  from member
  order by last_name, first_name, cad_num
  )
  as subquery
where (jan_code is not null and jan_code <> 23)
  or (feb_code is not null and feb_code <> 23)
  or (mar_code is not null and mar_code <> 23)
  or (apr_code is not null and apr_code <> 23)
  or (may_code is not null and may_code <> 23)
  or (jun_code is not null and jun_code <> 23)
  or (jul_code is not null and jul_code <> 23)
  or (aug_code is not null and aug_code <> 23)
  or (sep_code is not null and sep_code <> 23)
  or (oct_code is not null and oct_code <> 23)
  or (nov_code is not null and nov_code <> 23)
  or (dec_code is not null and dec_code <> 23)
