//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserControl_schedule_assignment_assistant_intro {
    
    
    public partial class TWebUserControl_schedule_assignment_assistant_intro {
    }
}
