//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace donation_ack_email {
    
    
    public partial class TWebForm_donation_ack_email {
        
        /// <summary>
        /// UserControl_donation_ack_email_control control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl_donation_ack_email.TWebUserControl_donation_ack_email UserControl_donation_ack_email_control;
    }
}
