//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace serial_indicator_control_chart
  {


  public partial class TWebForm_serial_indicator_control_chart
    {
    }
  }
