//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace timeout {
    
    
    public partial class TWebForm_timeout {
        
        /// <summary>
        /// Title control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected new global::System.Web.UI.HtmlControls.HtmlGenericControl Title;
        
        /// <summary>
        /// UserControl_precontent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl_precontent.TWebUserControl_precontent UserControl_precontent;
        
        /// <summary>
        /// UserControl_session_interrupted_control control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl_session_interrupted.TWebUserControl_session_interrupted UserControl_session_interrupted_control;
        
        /// <summary>
        /// UserControl_postcontent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl_postcontent.TWebUserControl_postcontent UserControl_postcontent;
    }
}
