START TRANSACTION
;
--
-- 01-04
--
;
delete from resident_base where agency <> 'OPVRS' and house_num = '4200' and street_id = (select id from street where name = 'BATTERY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4205' and street_id = (select id from street where name = 'BATTERY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4208' and street_id = (select id from street where name = 'BATTERY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4209' and street_id = (select id from street where name = 'BATTERY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4212' and street_id = (select id from street where name = 'BATTERY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4213' and street_id = (select id from street where name = 'BATTERY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4216' and street_id = (select id from street where name = 'BATTERY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4217' and street_id = (select id from street where name = 'BATTERY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4221' and street_id = (select id from street where name = 'BATTERY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4225' and street_id = (select id from street where name = 'BATTERY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4229' and street_id = (select id from street where name = 'BATTERY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4232' and street_id = (select id from street where name = 'BATTERY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4233' and street_id = (select id from street where name = 'BATTERY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4237' and street_id = (select id from street where name = 'BATTERY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4240' and street_id = (select id from street where name = 'BATTERY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2201' and street_id = (select id from street where name = 'BAYLAKE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2208' and street_id = (select id from street where name = 'BAYLAKE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2209' and street_id = (select id from street where name = 'BAYLAKE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2212' and street_id = (select id from street where name = 'BAYLAKE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2213' and street_id = (select id from street where name = 'BAYLAKE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2216' and street_id = (select id from street where name = 'BAYLAKE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2217' and street_id = (select id from street where name = 'BAYLAKE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2221' and street_id = (select id from street where name = 'BAYLAKE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2300' and street_id = (select id from street where name = 'BAYLAKE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2301' and street_id = (select id from street where name = 'BAYLAKE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2304' and street_id = (select id from street where name = 'BAYLAKE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2305' and street_id = (select id from street where name = 'BAYLAKE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2308' and street_id = (select id from street where name = 'BAYLAKE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2309' and street_id = (select id from street where name = 'BAYLAKE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2312' and street_id = (select id from street where name = 'BAYLAKE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2313' and street_id = (select id from street where name = 'BAYLAKE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2316' and street_id = (select id from street where name = 'BAYLAKE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2333' and street_id = (select id from street where name = 'BAYLAKE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2300' and street_id = (select id from street where name = 'BAYVILLE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2301' and street_id = (select id from street where name = 'BAYVILLE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2304' and street_id = (select id from street where name = 'BAYVILLE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2305' and street_id = (select id from street where name = 'BAYVILLE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2308' and street_id = (select id from street where name = 'BAYVILLE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2309' and street_id = (select id from street where name = 'BAYVILLE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2312' and street_id = (select id from street where name = 'BAYVILLE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2313' and street_id = (select id from street where name = 'BAYVILLE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2317' and street_id = (select id from street where name = 'BAYVILLE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2320' and street_id = (select id from street where name = 'BAYVILLE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2324' and street_id = (select id from street where name = 'BAYVILLE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2328' and street_id = (select id from street where name = 'BAYVILLE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2329' and street_id = (select id from street where name = 'BAYVILLE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2332' and street_id = (select id from street where name = 'BAYVILLE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2336' and street_id = (select id from street where name = 'BAYVILLE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2340' and street_id = (select id from street where name = 'BAYVILLE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2341' and street_id = (select id from street where name = 'BAYVILLE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2344' and street_id = (select id from street where name = 'BAYVILLE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2345' and street_id = (select id from street where name = 'BAYVILLE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2348' and street_id = (select id from street where name = 'BAYVILLE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4208' and street_id = (select id from street where name = 'BEN GUNN RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4217' and street_id = (select id from street where name = 'BEN GUNN RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4219' and street_id = (select id from street where name = 'BEN GUNN RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4220' and street_id = (select id from street where name = 'BEN GUNN RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4224' and street_id = (select id from street where name = 'BEN GUNN RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4300' and street_id = (select id from street where name = 'BEN GUNN RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4301' and street_id = (select id from street where name = 'BEN GUNN RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4304' and street_id = (select id from street where name = 'BEN GUNN RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4305' and street_id = (select id from street where name = 'BEN GUNN RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4308' and street_id = (select id from street where name = 'BEN GUNN RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4309' and street_id = (select id from street where name = 'BEN GUNN RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4312' and street_id = (select id from street where name = 'BEN GUNN RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4313' and street_id = (select id from street where name = 'BEN GUNN RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4316' and street_id = (select id from street where name = 'BEN GUNN RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4317' and street_id = (select id from street where name = 'BEN GUNN RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4320' and street_id = (select id from street where name = 'BEN GUNN RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4321' and street_id = (select id from street where name = 'BEN GUNN RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4325' and street_id = (select id from street where name = 'BEN GUNN RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4328' and street_id = (select id from street where name = 'BEN GUNN RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4329' and street_id = (select id from street where name = 'BEN GUNN RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4300' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4308' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4311' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4312' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4316' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4317' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4320' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4321' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4324' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4329' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4337' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4401' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4404' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4405' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4409' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4413' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4416' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4417' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4424' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4425' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4429' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4432' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4433' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4437' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4440' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4441' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4444' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4452' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4453' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4456' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4457' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4465' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4469' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4473' and street_id = (select id from street where name = 'BLACKBEARD RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4200' and street_id = (select id from street where name = 'BOUNTY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4201' and street_id = (select id from street where name = 'BOUNTY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4205' and street_id = (select id from street where name = 'BOUNTY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4209' and street_id = (select id from street where name = 'BOUNTY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4212' and street_id = (select id from street where name = 'BOUNTY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4216' and street_id = (select id from street where name = 'BOUNTY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4217' and street_id = (select id from street where name = 'BOUNTY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4221' and street_id = (select id from street where name = 'BOUNTY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4224' and street_id = (select id from street where name = 'BOUNTY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4232' and street_id = (select id from street where name = 'BOUNTY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4139' and street_id = (select id from street where name = 'FIRST COURT RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4141' and street_id = (select id from street where name = 'FIRST COURT RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2200' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2204' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2208' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2212' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2213' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2216' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2217' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2220' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2221' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2224' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2225' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2232' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2233' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2236' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2300' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2301' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2308' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2309' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2312' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2400' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2413' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2416' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2421' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2425' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2429' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2432' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2500' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2504' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2505' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2508' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2509' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2512' and street_id = (select id from street where name = 'INDIAN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4204' and street_id = (select id from street where name = 'JOHN SILVER RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4205' and street_id = (select id from street where name = 'JOHN SILVER RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4208' and street_id = (select id from street where name = 'JOHN SILVER RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4209' and street_id = (select id from street where name = 'JOHN SILVER RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4212' and street_id = (select id from street where name = 'JOHN SILVER RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4300' and street_id = (select id from street where name = 'JOHN SILVER RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4304' and street_id = (select id from street where name = 'JOHN SILVER RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4305' and street_id = (select id from street where name = 'JOHN SILVER RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4308' and street_id = (select id from street where name = 'JOHN SILVER RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4309' and street_id = (select id from street where name = 'JOHN SILVER RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4312' and street_id = (select id from street where name = 'JOHN SILVER RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4313' and street_id = (select id from street where name = 'JOHN SILVER RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4316' and street_id = (select id from street where name = 'JOHN SILVER RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4317' and street_id = (select id from street where name = 'JOHN SILVER RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4320' and street_id = (select id from street where name = 'JOHN SILVER RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4321' and street_id = (select id from street where name = 'JOHN SILVER RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4328' and street_id = (select id from street where name = 'JOHN SILVER RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4200' and street_id = (select id from street where name = 'LOOKOUT RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4201' and street_id = (select id from street where name = 'LOOKOUT RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4204' and street_id = (select id from street where name = 'LOOKOUT RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4205' and street_id = (select id from street where name = 'LOOKOUT RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4208' and street_id = (select id from street where name = 'LOOKOUT RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4212' and street_id = (select id from street where name = 'LOOKOUT RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4216' and street_id = (select id from street where name = 'LOOKOUT RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4217' and street_id = (select id from street where name = 'LOOKOUT RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2301' and street_id = (select id from street where name = 'ROOKERY WAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2309' and street_id = (select id from street where name = 'ROOKERY WAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2313' and street_id = (select id from street where name = 'ROOKERY WAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2317' and street_id = (select id from street where name = 'ROOKERY WAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2321' and street_id = (select id from street where name = 'ROOKERY WAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2325' and street_id = (select id from street where name = 'ROOKERY WAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2329' and street_id = (select id from street where name = 'ROOKERY WAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2333' and street_id = (select id from street where name = 'ROOKERY WAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2337' and street_id = (select id from street where name = 'ROOKERY WAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2341' and street_id = (select id from street where name = 'ROOKERY WAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2345' and street_id = (select id from street where name = 'ROOKERY WAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2349' and street_id = (select id from street where name = 'ROOKERY WAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2353' and street_id = (select id from street where name = 'ROOKERY WAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2357' and street_id = (select id from street where name = 'ROOKERY WAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2364' and street_id = (select id from street where name = 'ROOKERY WAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2365' and street_id = (select id from street where name = 'ROOKERY WAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2369' and street_id = (select id from street where name = 'ROOKERY WAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2373' and street_id = (select id from street where name = 'ROOKERY WAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4200' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4204' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4209' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4212' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4213' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4216' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4217' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4220' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4221' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4224' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4225' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4228' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4300' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4301' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4304' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4305' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4309' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4312' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4313' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4316' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4317' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4320' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4321' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4324' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4328' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4329' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4332' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4333' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4336' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4340' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4341' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4400' and street_id = (select id from street where name = 'SANDY BAY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4305' and street_id = (select id from street where name = 'SEA CHEST RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4308' and street_id = (select id from street where name = 'SEA CHEST RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4309' and street_id = (select id from street where name = 'SEA CHEST RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4312' and street_id = (select id from street where name = 'SEA CHEST RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4313' and street_id = (select id from street where name = 'SEA CHEST RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4316' and street_id = (select id from street where name = 'SEA CHEST RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4317' and street_id = (select id from street where name = 'SEA CHEST RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4320' and street_id = (select id from street where name = 'SEA CHEST RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4321' and street_id = (select id from street where name = 'SEA CHEST RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4324' and street_id = (select id from street where name = 'SEA CHEST RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2900' and street_id = (select id from street where name = 'SHORE DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4097' and street_id = (select id from street where name = 'SHORE DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4200' and street_id = (select id from street where name = 'SHORE DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4300' and street_id = (select id from street where name = 'SHORE DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4357' and street_id = (select id from street where name = 'SHORE DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4360' and street_id = (select id from street where name = 'SHORE DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4400' and street_id = (select id from street where name = 'SHORE DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4408' and street_id = (select id from street where name = 'SHORE DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4417' and street_id = (select id from street where name = 'SHORE DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4425' and street_id = (select id from street where name = 'SHORE DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4444' and street_id = (select id from street where name = 'SHORE DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4457' and street_id = (select id from street where name = 'SHORE DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4460' and street_id = (select id from street where name = 'SHORE DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4464' and street_id = (select id from street where name = 'SHORE DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4492' and street_id = (select id from street where name = 'SHORE DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '4493' and street_id = (select id from street where name = 'SHORE DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2305' and street_id = (select id from street where name = 'TREASURE ISLAND DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2308' and street_id = (select id from street where name = 'TREASURE ISLAND DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2309' and street_id = (select id from street where name = 'TREASURE ISLAND DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2312' and street_id = (select id from street where name = 'TREASURE ISLAND DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2304' and street_id = (select id from street where name = 'TRELAWNEY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2305' and street_id = (select id from street where name = 'TRELAWNEY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2308' and street_id = (select id from street where name = 'TRELAWNEY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2309' and street_id = (select id from street where name = 'TRELAWNEY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2317' and street_id = (select id from street where name = 'TRELAWNEY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2321' and street_id = (select id from street where name = 'TRELAWNEY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '2501' and street_id = (select id from street where name = 'WINDY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'CBVRS' and house_num = '2504' and street_id = (select id from street where name = 'WINDY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4236' and street_id = (select id from street where name = 'BATTERY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '4213' and street_id = (select id from street where name = 'BEN GUNN RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency <> 'OPVRS' and house_num = '2361' and street_id = (select id from street where name = 'ROOKERY WAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
;
--
-- 02-04
--
;

;
COMMIT