START TRANSACTION
;
ALTER TABLE `member`
  ADD COLUMN `be_placeholder` TINYINT NOT NULL DEFAULT FALSE
,
  ADD COLUMN `be_flight_medic` TINYINT NOT NULL DEFAULT FALSE
,
  ADD COLUMN `be_marine_medic` TINYINT NOT NULL DEFAULT FALSE
;
COMMIT