START TRANSACTION
;
delete from resident_base where agency = 'CBVRS' and house_num = '4841' and street_id = (select id from street where name = 'BRIGADOON DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'KVRS' and house_num = '2701' and street_id = (select id from street where name = 'BACH LN' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'KVRS' and house_num = '2112' and street_id = (select id from street where name = 'FARMINGDALE CIR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'KVRS' and house_num = '1960' and street_id = (select id from street where name = 'WINTERHAVEN DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'KVRS' and house_num = '4112' and street_id = (select id from street where name = 'CONWAY CIR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'KVRS' and house_num = '1301' and street_id = (select id from street where name = 'DOCKSIDE CT' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'KVRS' and house_num = '1037' and street_id = (select id from street where name = 'GLEN WILLOW DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'KVRS' and house_num = '1348' and street_id = (select id from street where name = 'NESBITT DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'KVRS' and house_num = '1513' and street_id = (select id from street where name = 'WOODBERRY CT' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'KVRS' and house_num = '3308' and street_id = (select id from street where name = 'CLUB HOUSE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '3308' and street_id = (select id from street where name = 'CLUB HOUSE RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '761-111' and street_id = (select id from street where name = 'ALLIANCE DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '761-237' and street_id = (select id from street where name = 'ALLIANCE DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '2025' and street_id = (select id from street where name = 'BIERCE DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '1637' and street_id = (select id from street where name = 'FLAMMARION DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '900-471' and street_id = (select id from street where name = 'FLEET DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '985-266' and street_id = (select id from street where name = 'FLEET DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '985-646' and street_id = (select id from street where name = 'FLEET DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '1528' and street_id = (select id from street where name = 'GALVANI DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '2017-335' and street_id = (select id from street where name = 'GENERAL BOOTH BLVD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '977' and street_id = (select id from street where name = 'GIDEON RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '2616' and street_id = (select id from street where name = 'MECKLEY CT' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '2136' and street_id = (select id from street where name = 'ROSEWELL DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '2937' and street_id = (select id from street where name = 'BREEZY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '2609' and street_id = (select id from street where name = 'BROAD BAY RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '1804' and street_id = (select id from street where name = 'DUKE OF NORFOLK QUAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '1840' and street_id = (select id from street where name = 'DUKE OF NORFOLK QUAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '1850' and street_id = (select id from street where name = 'DUKE OF YORK QUAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '2548' and street_id = (select id from street where name = 'FALCON CRES' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '1724' and street_id = (select id from street where name = 'GREEN HILL RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '2905' and street_id = (select id from street where name = 'KEELINGWOOD CT' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '2624' and street_id = (select id from street where name = 'LANDVIEW CIR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '2308-301' and street_id = (select id from street where name = 'MARINERS MARK WAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '2317-301' and street_id = (select id from street where name = 'MARINERS MARK WAY' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '3185' and street_id = (select id from street where name = 'PAGE AVE' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '1701' and street_id = (select id from street where name = 'RALLY DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '3100-1214' and street_id = (select id from street where name = 'SHORE DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '3100-555' and street_id = (select id from street where name = 'SHORE DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '2418' and street_id = (select id from street where name = 'STARFISH RD' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '2259' and street_id = (select id from street where name = 'WAKE FOREST ST' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '2205' and street_id = (select id from street where name = 'WINDWARD SHORE DR' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
delete from resident_base where agency = 'VBVRS' and house_num = '1930' and street_id = (select id from street where name = 'WOODSIDE LN' and city_id = (select id from city where name = 'VIRGINIA BEACH'));
;
COMMIT
