//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace report_departures_effective_today {
    
    
    public partial class TWebForm_report_departures_effective_today {
        
        /// <summary>
        /// UserControl_common_header_bar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl_common_header_bar.TWebUserControl_common_header_bar UserControl_common_header_bar;
        
        /// <summary>
        /// UserControl_departures_effective_today_control control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl_departures_effective_today.TWebUserControl_departures_effective_today UserControl_departures_effective_today_control;
    }
}
