//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserControl_drop_down_datetime {
    
    
    public partial class TWebUserControl_drop_down_datetime {
        
        /// <summary>
        /// UserControl_drop_down_date_control control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl_drop_down_date.TWebUserControl_drop_down_date UserControl_drop_down_date_control;
        
        /// <summary>
        /// UserControl_drop_down_time_of_day_control control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl_drop_down_time_of_day.TWebUserControl_drop_down_time_of_day UserControl_drop_down_time_of_day_control;
    }
}
